### PR TITLE
Implement live MIDI input

### PR DESCRIPTION
**Pull request by minihui**
So this is my code to support live MIDI input. A new Label and a ComboBox is add to the UI, and a few codes for the live MIDI input. It's not too much code so it should be pretty easy to understand and merge them. Actually we can change the MIDI port on the fly but I didn't see the requirement to do that so I'll just do the same as reselecting the COM port, do the shutdownSequencer().

### CODE REVIEW

**Comment by minihui** [comment]
Please be noticed the positions of label4 and the jcombobox is not match, since the code was manually modified. Too many differences were generated if I only upload the files saved with my IDE. So you may like to rearrange the position of those 2 objects.

**Comment by minihui** [comment]
Here's another fix for 2 issues.

1) Once pitch bending is invoked, the pitch is one octave higher. So it's made half.
2) If more than two keys is pressed, period 0 was sent to Arduino immediately right after any of them is released. So I add a array to keep trace of the number of the keys pressed, and only send a period 0 after all the keys are released. Before the release of the last key, the period of the last note is sent.

The only file affected in this update is MoppyPlayer.java.

**Comment by minihui** [comment]
Ignore the second fix please, it's not well coded and may cause error. That code is removed.

**Comment by minihui** [comment]
Cleaned up as much as I can...

**Comment by duggan** [comment]
Cool, going to check this out myself once I've got my synth to hand :)

**Comment by minihui** [comment]
Yeh, please report if it is working or not. It builds on my Mac with -d32 parameter in NetBeans because rxtxComm won't compile on 64-bit Mac at the moment. You can use a MIDI loopback driver like built-in IAC Driver on Mac or LoopBe1 on Windows to play with DAWs. Have fun :P

**Comment by duggan** [comment]
I've actually got a [fork/branch](https://github.com/duggan/Moppy/tree/osx-lion) with the correct rxtxComm for 64-bit OSX.

Edit: actually, that's `librxtxSerial.jnilib` that was changed, but I don't believe I've had to muck around with 32 bit parameters.

I haven't submitted it as a PR because frankly it's been years since I've touched Java, and I haven't gone through the various bits and pieces that Netbeans changed to weed out what is and is not a required change.

Either way, looking forward to seeing if I can get your patch working, cheers :)

**Comment by jerossen** [comment]
I'm pretty new to Java, but I get this error when I press connect or load a MIDI file:

http://pastebin.com/aVG6qvUK

Hope it helps :)
-Jesper

**Comment by minihui** [comment]
That's not expected and I can't really tell why your device can't be opened, as I'm new to Java too, this is my first edit to a Java project... 

What's your MIDI device selection on the right upper corner? The message showed your 3rd device is selected. I can't do more on this because of my Java experience I think, but what I can do is to bypass the faulty device and avoid crashing the program :( The "MIDI port error" message comes from a try...catch actually.

The modified code should be ready soon. Please test it. The program shouldn't crash again

**Comment by jerossen** [comment]
Still crashing :(
Happens no matter what device i select.

Here's a debug for every device I have available (Don't know if the error is different):

Gervill:
http://pastebin.com/FKtbeT2z

Microsoft MIDI Mapper:
http://pastebin.com/StkNhyfc

Microsoft GS Wavetable Synth:
http://pastebin.com/6GJbbBe4

Real Time Sequencer:
http://pastebin.com/nVvvnuad

It dosen't post any errors with Real Time Sequencer, but the Arduino dosen't seem to recieve any input :/

**Comment by minihui** [comment]
Jesper, did you update the code in MoppySequencer.java? 
line 44 was : midiIn.setReceiver(mp); and it was moved inside the try{} above now.
now line 44 is sequencer.open();

Now it should act exactly the same as before if a MIDI port error is invoked, I think...

**Comment by minihui** [comment]
Jesper, if the Java program didn't crash, it should be able to play your .mid file and your Arduino should receive something while playing. (RX led flashing, with the correct COM port selected)

My code didn't filter MIDI output only devices so I guess if such a device is selected and opened for MIDI input it would crash. I'll try to modify the code if possible. 

It's 4:45 am and I really need to get some sleep :s Good luck with it and let me know if it works now.

**Comment by jerossen** [comment]
Same here with the sleep :P
Testing it as soon as possible tomorrow. :p

**Comment by jerossen** [comment]
Ok. Just tested again. It stopped posting errors, and I am able to play MIDI files.
But it still says:

MIDI port selected: [Midi port]
MIDI port error: [Midi port]

At every device except Real TIme Sequencer. Also, the arduino dosen't respont to any live MIDI data. (Only the files)

**Comment by samphonic** [comment]
I'm following this as best I can, I've been on vacation so I haven't had a chance to look at the actual code for the changes.  Hopefully I'll get a chance to this week sometime.  I'm psyched that there's code contributions though.  =)

**Comment by minihui** [comment]
Jesper, sorry for being away for quite a while. The thing is, in our situation we'll need a logical MIDI device which has a MIDI input (to the system, output of the device). My code enumerates all logical MIDI devices, no matter if they have MIDI input or not. So when it tries to get MIDI data from a MIDI input that doesn't logically exist, it would crash. To play the floppies with live MIDI data, you'll need either a physical MIDI output device (a MIDI keyboard with 5-pin MIDI output or USB, or a phone or something like that which has its way connecting to the computer), a software sequencer, or a software instrument. If you use a physical device, corresponding MIDI port should be selected. If you use software however, a MIDI loop back driver, which will route your software's MIDI output to the loop back driver's MIDI input port, is needed. (IAC driver on Mac, LoopBe1 on Win)

As I'm so new to Java, I really don't know how to only enumerate devices that have a MIDI input port. Sorry

**Comment by jerossen** [comment]
Got it working after installing LoopBe1 :D 
By the way, do you think it would be possible to make a Check Box to make it split up several tones from one channel, to the other drives? For making it easier to play chords.

-Jesper

**Comment by minihui** [comment]
Wow that's a very interesting idea. I think what we gonna do is to discard the channel info and rearrange the new note to a free channel. The down side would be possibly generating different sound when the notes are coming from the same MIDI channel because they are remapped to different floppy channels. Or on our chord mode we could only accept channel 1 then remap the notes :)

**Comment by jerossen** [comment]
Only accepting channel 1 will not affect anything, as it would be that channel that is used by, for example, a MIDI Keyboard :)

**Comment by samphonic** [comment]
Alright, I need to just get off my lazy butt and incorporate some of this code.  I did actually find a way to find only input devices, so I could probably get that working.

Also, I think I agree with cfreakDK on the chords: since the MIDI keyboard would only be sending notes on a single channel, you can just spread those notes out over several drives.  When I implemented it, I basically just kept track (in the Java code) of which notes were playing (up to 8, since that's how many drives I had) and would assign notes to the first available (non-playing) drive.  So single notes would go into drive 1, the second into drive 2, etc.

This worked fairly well, but the downside is drive 1 _always_ plays and drive 8 pretty much never plays at all.  It might be neat to try to split of the drives by range on the keyboard and assign based on that (i.e. low-notes prefer drive 1 and high-notes prefer 8), but it starts to get complicated at that point.

**Comment by minihui** [comment]
Yes, but a sequencer (DAW) maybe used to play multi-channel MIDIs. That's the easiest way to compose or modify MIDIs for floppies exclusively. So a switch for the chord mode is necessary I suppose. 

Thanks again for your Moppy!

**Comment by samphonic** [comment]
Alright, I've been distracted but it's time to turn my attention back to this pull request, if just momentarily, before I make some big changes to the code to support the project I'm working on currently.

I'm going to try to test minihui's changes to the code tonight and test things on my drives at home.  If everything works well, I'll merge this pull request and maybe incorporate a couple other code changes by others.

I'm then going to fork out the code (as soon as I figure out how to best do this with github) into a MoppyAdvanced project that'll beef up some of the options in the interface.  Most notably, I'd like to provide a configurable mapping for each input-channel to an output channel/type.  This would allow users to re-map which channels are fed to which drive, but should also allow the use of multiple Arduinos or output devices, where each channel can be assigned to a different device.  The motivation being that my next project accepts MIDI input directly, so I'd like to be able to continue to use Moppy to run my 8 drives, but also pass-on any MIDI notes on a channel (e.g. 9) to a MIDI-out port.  Or, in the future, to a different COM port with another Arduino to control lights or something else.

I'd like to throw in an option to allow drive-pooling (as previously discussed) so that multiple notes can be played across several drives (like when accepting MIDI input from a keyboard).  Not sure how I'll do that yet, but I'll try to get that in there too.

(If I get antsy, I might start working on the interface first and pull minihui's code after, but I feel like that will be more complicated)

**Comment by samphonic** [comment]
=/ Alright, so, I pulled in minihui's code on my local machine, and it does look great (I can't test it yet 'cus I'm not at home), but I'm having trouble figuring out how I'd cleanly incorporate it into the new UI.

I'm a little torn here, because I think the easiest and quicket way to get the advanced configuration working is to scrap most of the current high-level code and start again from scratch (keeping just some of the low level files like the Sequencer and Bridge), but I don't want to just abandon the work done here, especially the contributions from you guys.

Current plan of action will actually probably be to leave the current master branch here untouched, and just pull in some bug-fixes.  I'll probably forward people to minihui's fork if they need MIDI-IN support now, and the new version will have MIDI-IN support wrapped in from the beginning.  If I use any code from anyone's repositories I will try to heavily acknowledge them in the code comments and in the read me.

I'm open to suggestions though on how you guys think best to move forward.  If I don't hear anything in a few days I'll close up this pull request.  Thank you again for all your help and contributions, hopefully I can try to keep things moving.

**Comment by samphonic** [comment]
As previously pondered, I've created a new branch of code that supports live MIDI input as well as having some more features and being a little bit more modular for adding future things:

https://github.com/SammyIAm/Moppy/tree/moppy-advanced

Apologies to minihui whose excellent code won't be getting directly pulled in to this base, but I'm going to leave this basic Moppy just as it is.  I may eventually try to make MoppyAdvanced the default code branch if I can figure out how to do it.  Thanks for the input!

**Pull request closed without merging**
