### PR TITLE
Raspberry coud play music too

### PR DESCRIPTION
**Pull request by tg44**
I implemented your code to Raspberry Pi. I let in the arduino code too, reorganize the code a bit. The graphical interface get very pure modifications. Some minor bug coud be there, but i think its working. (I cant try it with multiple floppies and after the code integration, but it worked separately.) It's use udp instead of serial. In the future the tcp coud be more effective.

I will see whats modified in the advanced, and I make an another request to there if you like this idea.

### CODE REVIEW

**Comment by samphonic** [comment]
Cool!  I may not get to merging this right away since I don't have things in place to do testing.  Is there any way you could commit this to your fork of the code though?  That way I can direct people looking to play with this on a Raspberry Pi in your direction for a starting point.

**Comment by tg44** [comment]
I made a new branch for this there: https://github.com/tg44/Moppy/tree/moppy-raspberry I will have more time in a next week, and I will play the with the RPI again. I will get more drivers too.

**Comment by tg44** [comment]
Its working. Not my best work in the gui, but its working... (I tested with 4 drivers.)

**Comment by samphonic** [comment]
Hooray!!

**Comment by felixphew** [comment]
Thinking about how best to handle this, I reckon: close this pull request, let Sammy create the new branch, and then propose the pull request to that? Either that or have Sammy give you rights to the repository, because you will probably end up maintaining this part of the project anyway, seeing as you wrote it!

**Comment by samphonic** [comment]
Is there any reason not to just let tg44's branch be the authoritative RasPi branch, and just link to it, rather than creating a new branch here?  (I'm a bit new to this GitHub thing)

**Comment by samphonic** [comment]
Actually, while I'm asking for advice on GitHub anyway (and since you seem to know what's going on): I'd like to make the MoppyAdvanced branch the default branch for this project.  How would I go about doing that?

**Comment by GrahamCampbell** [comment]
Go into https://github.com/SammyIAm/Moppy/settings, and underneath the repo name, you can select the default branch.

**Comment by samphonic** [comment]
Wow, thank you, that was easy!

**Comment by atabb123b** [comment]
how do i access the raspi music code

**Comment by AAllport** [comment]
jdk 1.7?

**Comment by tg44** [comment]
Yes, if I remember well its 1.7 . And its on the rpi branch. Or there is not really rpi branch anymore so:
https://github.com/tg44/Moppy/tree/moppy-raspberry

**Pull request closed without merging**
